### PR TITLE
Allow falsy defaultValue

### PR DESCRIPTION
**Pull request by jonapgar**
Need to allow falsy defaultValue such as '' or null to be used in conjunction with options.returnEmptyString or options.returnNull

### CODE REVIEW

**Comment by jonapgar** [comment]
This allows you to do something like this, which works in v1.x

var phrase = t('ns:missing',{defaultValue:null}) || somethingExpensive();

or 

var phrase = t('ns:foo') +  t('ns:missing',{defaultValue:'}) + t('ns:bar');

**Comment by jamuhl** [comment]
this allows `undefined` as value too. not sure if we should limit to `''` and `null`. As undefined would need special handling in backends (as not JSON serializable).

so check should be `&& options.defaultValue !== undefined`

**Comment by jonapgar** [comment]
Yeah I thought about that too. In any event the undefined would not pass
the next  *isValidLookup *condition a few lines down.

**Comment by jamuhl** [comment]
can you change the PR to `&& options.defaultValue !== undefined`? can be merged after that change.

**Comment by jamuhl** [comment]
i18next@2.5.0 allows all but undefined

**Pull request closed without merging**
