### PR TITLE
perf(interpolator): use object deconstruction

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
The code used in this file can benefit from the use of object deconstruction and optional changing. Both of these reduce the amount of property lookups the engine needs to do which should help improve performance. Perhaps more important it cuts out unneeded code and allows for better mangling by rollup, cutting down the size of the minified files a bit, without impacting functionality.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [x] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
We did not use the optional chaining operator etc... because in the past there has been some i18next usage in environments where this was not supported... for example we wanted to still support Node v12 (https://github.com/i18next/i18next/issues/1948) and that node version is not able to understand that syntax...
Do you have some tests that proofs that performance is significially better with your change?

**Comment by VIKTORVAV99** [comment]
> We did not use the optional chaining operator etc... because in the past there has been some i18next usage in environments where this was not supported... for example we wanted to still support Node v12 (#1948) and that node version is not able to understand that syntax... Do you have some tests that proofs that performance is significially better with your change?

I have not made any performance benchmarking as I was mostly looking to cut down the size of the generated code bundles.

I'd be happy to skip the optional chaining if that means it can be merged quicker (with just the object deconstruction) but is supporting node 12 still something that is required from your side? Node 12 has been out of LTS for almost 4 years soon.

**Comment by adrai** [comment]
> is supporting node 12 still something that is required from your side?

not from my side personally, but I'm sure there are some situations in userland that still uses old node versions...

So for now, yes if you remove the optional chaining we can merge that immediately...

**Comment by VIKTORVAV99** [comment]
> > is supporting node 12 still something that is required from your side?
> 
> not from my side personally, but I'm sure there are some situations in userland that still uses old node versions...
> 
> So for now, yes if you remove the optional chaining we can merge that immediately...

Will do that then and perhaps open an issue about bumping the minimum node version so it can be discussed?

**Comment by adrai** [comment]
> Will do that then and perhaps open an issue about bumping the minimum node version so it can be discussed?

we can do that for the next major version... but I don't think there are a lot of benefits to make a new major version to just drop older node.js versions...

**Comment by VIKTORVAV99** [comment]
> > Will do that then and perhaps open an issue about bumping the minimum node version so it can be discussed?
> 
> we can do that for the next major version... but I don't think there are a lot of benefits to make a new major version to just drop older node.js versions...

Would it be fine if I opened a PR to switch to optional chaining across all of the files then? Then you can merge it whenever you want.

**Comment by adrai** [comment]
> Would it be fine if I opened a PR to switch to optional chaining across all of the files then? Then you can merge it whenever you want.

You can, but that will not be merged so soon...

**Comment by VIKTORVAV99** [comment]
> > Would it be fine if I opened a PR to switch to optional chaining across all of the files then? Then you can merge it whenever you want.
> 
> You can, but that will not be merged so soon...

That's fine from my side 👍🏻

**Comment by adrai** [comment]
thank you... it's included in v23.11.4

**Pull request merged**
