### PR TITLE
Allow to fallback to key when trans string is empty

### PR DESCRIPTION
**Pull request by limdauto**
I think it's sensible to display the key (sometimes people use English string or whichever default language they use as key) instead of an empty string.

### CODE REVIEW

**Comment by captolia** [comment]
+1

**Comment by timseverien** [comment]
+1

**Comment by jamuhl** [comment]
if i accept this PR the other 50% will complain that they want empty string as an acceptable value (was like this before).

make that depending on a setting provide on init `showKeyIfEmpty` (like fallbackOnEmpty, fallbackOnNull)

**Comment by limdauto** [comment]
@jamuhl cool. I will add that init option. Thanks for replying.

**Comment by limdauto** [comment]
@jamuhl sorry for the delay. I have added the init option. Could you please take a look? Thnx

**Comment by jamuhl** [comment]
perfectm, thank you...will merge this asap.

**Pull request merged**
