### PR TITLE
Allow translate function to skip interpolation and return raw values instead

### PR DESCRIPTION
**Pull request by manixate**
This PR allows skipping interpolation but still allows post processing of the returned values. Let me know if you want post processing to be skipped as well. I allowed it because post processing already has `options.applyPostProcessor` to enable or disable it.

Fixes: #1007

### CODE REVIEW

**Comment by jamuhl** [comment]
@manixate thanks for providing this PR. Agree with you excluding postProcessing can be done by using the other option. Will merge and publish this now.

**Comment by jamuhl** [comment]
published in i18next@11.3.0

thanks again for providing this complete PR

**Comment by manixate** [comment]
I agree on:

> skipInterpolation is not applied if i18nFormat is set -> different parser (eg. ICU)

For my use-case it is perfectly fine but the reason I skipped the whole i18nFormat was because the linked issue mentioned performance reasons and I thought skipping would be beneficial.

**Comment by jamuhl** [comment]
the issue was created before having those additional i18nFormats...so not affected there when using those format plugins...

**Pull request merged**
