### PR TITLE
perf(size): Adds a isString utility

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Adds a isString utility just like in https://github.com/i18next/react-i18next/pull/1763 to reduce code duplication. This alone reduces the size of the minified output by roughly 0.5 kB.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
On a related note is it possible import helpers from the core i18next package (this one) in the framework specific ones?

**Comment by adrai** [comment]
> On a related note is it possible import helpers from the core i18next package (this one) in the framework specific ones?

theoretically yes, but it's not part of the "public" i18next api (yet)

**Comment by adrai** [comment]
included in v23.16.2

**Comment by VIKTORVAV99** [comment]
> > On a related note is it possible import helpers from the core i18next package (this one) in the framework specific ones?
> 
> theoretically yes, but it's not part of the "public" i18next api (yet)

Might be nice to do so loggers and utilities can be reused without much effort.

**Comment by adrai** [comment]
logger is already used via this.services

**Comment by VIKTORVAV99** [comment]
> logger is already used via this.services

Then why is react-i18next defining its own warning functions in its utility file?

**Comment by adrai** [comment]
I think because most warning needs only to be warned once... and there is not alway access to the i18next core... (am I right, @jamuhl ?)

**Comment by adrai** [comment]
normal i18next plugins uses the core logger: https://github.com/i18next/i18next-http-backend/blob/master/lib/index.js#L157

**Comment by jamuhl** [comment]
logger is more about using init option debug: true -> get information when needed (mute in production)

if it's a regular warning (like wrong usage of useTranslation before init) there is no need to make that dependent on debug true...it's a basic console.warn

**Pull request merged**
