### PR TITLE
Feature/add withT interface

### PR DESCRIPTION
**Pull request by tkow**
Check it if https://github.com/i18next/i18next/pull/1163 pull request is accepted and

- export  extension-able intererface  for outsider library.

More specific, look at the https://github.com/i18next/react-i18next/pull/665 discussion ,too.

### CODE REVIEW

**Comment by jamuhl** [comment]
@rosskevin is it ok for you if i ping you for typescript related PR's - as my own knowledge is zero on typings and @schettino seems to have left the boat for typescript related questions. If so i would love to grant you access to the needed repos and mention you under contributors?

**Comment by rosskevin** [comment]
@jamuhl yes please add me to both repos and I'll help maintain the typescript definitions.

Regarding this and the other PR in this repo, we do not have tests here so it is not safe to merge yet.

We need to add typescript usage tests here first, get them passing then these PRs can be re-tested.

@tkow are you interested in PRing typescript usage tests like I did in react-i18next here for baseline testing or do you want to wait until I have time to add them?

**Comment by jamuhl** [comment]
@rosskevin invitations sent

**Comment by tkow** [comment]
@rosskevin Yes I am. But, I have no idea how these changes are proved safety, though these looks as don't change any old behaviors  because I didn't change any other types without i18n.t and the default types are same before, especially about first PR. However, I understand checking is never too much to do and I don't know still this project well. As you say, I'll check asap tests and check no doubt behavior.

**Comment by tkow** [comment]
@rosskevin 
Ah..., I understood what you mean. This repository does'nt have any ts test yet.
Okey. I'll try to implement with referring to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/i18next/i18next-tests.ts .

**Comment by tkow** [comment]
@rosskevin @jamuhl 
I have done this. If it has problem, please let me know.

**Comment by rosskevin** [comment]
Thanks @tkow. I was actually looking to add the existing baseline tests as a different standalone PR, get them to pass and merge it, then try test your new PRs. It would give us confidence that we were not introducing a breaking change. If you don't want to take time to separate, I understand, I'll do it next week when I am back in the office.

**Comment by tkow** [comment]
@rosskevin 
Actually, I have separated already two PR requests  from https://github.com/i18next/i18next/pull/1163. But I noticed mistake to contaminate WithT Interface's commit and removed it, I'm sorry if you get confused. Though #1163 is enough for me as ever test is nothing, if I need to separate commits in that PR. I'll do it because it can take easily by cherry-picking.

**Comment by tkow** [comment]
I made separated PR. Thanks for navigation.

**Comment by rosskevin** [comment]
I'm going to close this PR.  Please re-submit the change based on the latest `master` because I've merged the test setup and prettier changes.  It makes this one too noisy so best to just start new, I know there are only a few lines changed here.

Thanks @tkow

**Pull request closed without merging**
