### PR TITLE
Add support to proper augment PluginOptions type

### PR DESCRIPTION
**Pull request by pedrodurek**
This is the first PR that solves this problem: https://github.com/i18next/i18next/issues/1578
[Another one](https://github.com/locize/i18next-locize-backend/pull/340) will be created under `i18next-locize-backend` that depends on this.

It should have no breaking changes to users.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
Would also other backends need to be updated?
like:

- https://github.com/i18next/i18next-http-backend
- https://github.com/i18next/i18next-fs-backend
- ...

or other plugins like: https://github.com/i18next/i18next-browser-languageDetector ?

**Comment by adrai** [comment]
https://github.com/locize/i18next-locize-backend/pull/340

**Comment by pedrodurek** [comment]
I'm going to take a look at the other repos.

**Comment by pedrodurek** [comment]
Hey @adrai, let me know if there any remaining plugins.

**Comment by adrai** [comment]
Thank you for your help.
There probably are others... but if [this](https://github.com/i18next/i18next-browser-languageDetector/pull/235) is all there is to do... it's doable 😉

hope @jamuhl can have a look at it so we can create the appropriate releases...

If I've understood correctly this should not be breaking for neighter i18next nor the plugins, right?

**Comment by pedrodurek** [comment]
No problem!!! Yeah, it should have **no** breaking changes on both sides

**Comment by mrrotberry** [comment]
@pedrodurek , hmm, looks like you broke support of `i18next-chained-backend`, library for combine multiple of the existing backends( I'm talking about such a case:

```
i18nextInstance
  .use(I18NextChainedBackend)
  .init({
    backend: process.env.NODE_ENV === 'production'
      ? {
          backends: [LocalStorageBackend, I18NextHttpBackend],
          backendOptions: [localStorageBackendConfig, httpBackendConfig],
        }
      : {
          backends: [I18NextHttpBackend],
          backendOptions: [httpBackendConfig],
        },
    });
```

**Comment by pedrodurek** [comment]
Hey @mrrotberry, yeah, It was reported yesterday, I'm on it! 😃

**Comment by mrrotberry** [comment]
OK, sorry didn't see 😃  could you tell me where this issue was discussed and where I could keep track of it?)

**Comment by pedrodurek** [comment]
Sure! https://github.com/i18next/i18next-http-backend/issues/58

**Comment by mrrotberry** [comment]
thank you very much and have a nice day)

**Comment by adrai** [comment]
@mrrotberry should be fixed with the new i18next-chained-backend version

**Comment by mrrotberry** [comment]
@adrai I confirm, the typing works fine, there are no errors. Thank you very much 👍

**Comment by adrai** [comment]
You have to thank @pedrodurek
he is the master of TypeScript 😉

**Pull request merged**
