### PR TITLE
Update Interpolator.js

### PR DESCRIPTION
**Pull request by DmitriyMaximov**
Resolve https://github.com/i18next/i18next/issues/1306

### CODE REVIEW

**Comment by jamuhl** [comment]
thank you. was published in i18next@17.0.10

**Comment by Monokai** [comment]
This throws when a variable does not exist, whereas it's better how it worked before, when it just didn't output anything. Try: `i18next.t('hello {{-name}}')` when the variable `name` doesn't exist.

**Comment by jamuhl** [comment]
@Monokai sorry for that - will provide a fix later today: Guess i will add the check like https://github.com/i18next/i18next/pull/1307/files#diff-c4c32a53d5f4662890bf17b0a8fd47bcR108

**Comment by jamuhl** [comment]
@Monokai can you try with i18next@17.0.11

**Comment by Monokai** [comment]
Solved. Thanks for the quick fix! :)

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Pull request merged**
