### PR TITLE
Added official MIT header to license

### PR DESCRIPTION
**Pull request by vijairamcharan**
Added the official license header according to http://opensource.org/licenses/MIT. This will be of great help for preventing legal issues for users of this library. Would be great if you can merge it.

### CODE REVIEW

**Comment by archer96** [comment]
Would also be great to add

```js
license: "MIT",
```

to https://github.com/i18next/i18next/blob/master/package.json

**Comment by vijairamcharan** [comment]
@archer96 good one, added commit

**Comment by jamuhl** [comment]
do you need a published version with licenses change? or is it enough for next official release?

**Comment by vijairamcharan** [comment]
@jamuhl for me it already *great* that this was merged really fast :+1: . I can wait until the next official release. tx, so far...

**Comment by jamuhl** [comment]
@vijairamcharan ok...perfect....else just let me know...no big deal to publish.

thanks...for helping on licence stuff.

**Pull request merged**
