### PR TITLE
[TS] Typescript imports

### PR DESCRIPTION
**Pull request by PierreAndreis**
## Problem
Imports were working for `esModuleInterop: true`, but not for `esModuleInterop: false` (default) users.

## Summary of previous discussions/experiments as requirements
- keep namespace
- make most tests running with `esModuleInterop:true` (not the other way around)
- make the one-off test `esModuleInterop:false`
- make the `esModuleInterop:false` use the `import * as syntax`
- make the `esModuleInterop:true` use the `import i18n, {TResult` syntax

## Changes
- Update typings to take in consideration that our `main` script in package.json is a cjs bundled file.
- Update tsconfig to `esModuleInterop` as true. This should reflect most of the ts users on browsers, as it is common to have this option enabled when using babel.
- Create tests to cover cases when `esModuleInterop` is false.

## Breaking changes
None.
Our typings were already broken if the user was not using `esModuleInterop`. This fixes it.

## Previous discussions
PR #1286
PR #1282
Issue #1271

### CODE REVIEW

**Comment by rosskevin** [comment]
@PierreAndreis thanks again for all the help here - this is surprisingly not a simple thing to accomplish.

My question comes to your claim that there are `no breaking changes`.  For people using `esModuleInterop:true`, are you saying that `import * as i18next` will still work for them, they can just optionally switch to `import i18next` at their leisure?

**Comment by PierreAndreis** [comment]
@rosskevin typings should be valid still. It will be up to them to optionally switch to `import i18next`.

**Comment by rosskevin** [comment]
I added the `exposedLegacy.test.ts` to confirm backward compatibility for `esModuleInterop: true` users.  They can now optionally use the simpler syntax.

@jamuhl this can be a patch release.

Big thank you to @PierreAndreis for putting in the work!

**Comment by PierreAndreis** [comment]
@rosskevin This was my first open source contribution and you made it easier. Thank you for helping out 🥇

**Comment by jamuhl** [comment]
published in i18next@17.0.7

**Comment by bhollis** [comment]
This is not backwards compatible.

Now, this line:

```
i18next.use(XHR)
```

Produces:

```
Argument of type 'I18NextXhrBackend' is not assignable to parameter of type 'BackendModule | LoggerModule | LanguageDetectorModule | LanguageDetectorAsyncModule | I18nFormatModule | ThirdPartyModule[]'.
```

**Comment by danielsogl** [comment]
The type `initReactI18next` for i18next-react is also missing but could be ignored with `// @ts-ignore`

**Comment by jamuhl** [comment]
PR welcome to fix this

**Pull request merged**
