### PR TITLE
Cope with null interpolation

### PR DESCRIPTION
**Pull request by alexrudall**
Cope with null value as well as undefined :)

### CODE REVIEW

**Comment by jamuhl** [comment]
if doing so, please also do it here: https://github.com/i18next/i18next/pull/1310/files#diff-c4c32a53d5f4662890bf17b0a8fd47bcL117

**Comment by alexrudall** [comment]
Hmm if I add this `test/interpolation.spec.js` line 426 fails, seems like it copes with it already? Sorry if I'm being dumb!

**Comment by jamuhl** [comment]
so this can be closed?

**Comment by alexrudall** [comment]
Sorry, I meant I don't think it's necessary to add the null check here as you suggested:

https://github.com/i18next/i18next/pull/1310/files#diff-c4c32a53d5f4662890bf17b0a8fd47bcL117

as it seems to be already covered by existing specs, which actually fail if I add the null check you suggested.

But I could be wrong! Apologies, I'm quite new to this library.

**Comment by jamuhl** [comment]
already late here - will merge it tomorrow

**Comment by jamuhl** [comment]
published in i18next@17.0.12

**Comment by alexrudall** [comment]
Thanks!

**Pull request merged**
