### PR TITLE
Adds promises API

### PR DESCRIPTION
**Pull request by jamuhl**
solves: https://github.com/i18next/i18next/issues/661

### CODE REVIEW

**Comment by jamuhl** [comment]
@isaachinman would be great if you take a quick look

**Comment by isaachinman** [comment]
I don't really understand the use of `utils.defer`. Why not just use a `Promise` wherever you need it? Also, I think you will need to explicitly return a promise from these functions to be able to successfully call `await` or `then`?

**Comment by jamuhl** [comment]
A Promise needs the resolving inside the passed function:

`new Promise(function(resolve, reject) { ... });`

but i need to call `resolve` from outside -> that is what the defer() enables:

it returns a Promise and enables calling resolve on it form outside.

https://github.com/i18next/i18next/pull/1130/files#diff-c573044ba770c7e0efcf82de26be326aR121 -> is a Promise

which get resolved here: https://github.com/i18next/i18next/pull/1130/files#diff-c573044ba770c7e0efcf82de26be326aR208

based on: http://lea.verou.me/2016/12/resolve-promises-externally-with-this-one-weird-trick/

**Comment by isaachinman** [comment]
Ah, I see now what you're saying. It's an OK pattern, but a little harder to follow. Haven't seen that before. Maybe we can add a link to that blog post as a comment inside the `utils.defer` function, so that people looking through the source can understand it quickly?

In general this looks good though.

As far as the test cases, it might be better/simpler to test like:

    typeof i18next.init().then === 'function'

**Comment by jamuhl** [comment]
@isaachinman Promises API was published in i18next@13.0.0

**Comment by isaachinman** [comment]
@jamuhl That is great news! We will start consuming it immediately at `next-i18next`.

**Pull request merged**
