### PR TITLE
ci: add `codeQuality` and `build` jobs

### PR DESCRIPTION
**Pull request by marcalexiei**
- Replaced `prettier` script with `format` and `format:fix` script
- Added a `codeQuality` job as described in the issue (#2142).
- In addition I also added a `build` job to assure that also build runs smoothly.
- `pretest` script no longer runs `lint` script
---

Due to the previous changes I renamed the `lint_and_test` workflow in `CI` to better reflect its purpose.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
Can you also adapt the README because of the github worfklow renaming? https://github.com/i18next/i18next/blob/master/README.md?plain=1#L3

btw: does the lint script not run anymore completely?

**Comment by marcalexiei** [comment]
> Can you also adapt the README because of the github worfklow renaming?

Sure!

---

> btw: does the lint script not run anymore completely?

The lint script is now executed explicitly inside `codeQuality` job. 
If you wish we could run it also on `pre-push` hook via `husky`.

**Comment by adrai** [comment]
Yes, maybe also pre-push would be good.

**Comment by marcalexiei** [comment]
I also added `format` script within the `pre-push` hook.
Better to have them fail locally than while running an action so you can have feedback quicker.

**Comment by adrai** [comment]
thx a lot

**Pull request merged**
