### PR TITLE
Allow boolean on keySeparator and nsSeparator

### PR DESCRIPTION
**Pull request by felixmosh**
Add the ability to pass `false` as nsSeparator & keySeparator

#### Checklist

- [X] only relevant code is changed (make a diff before you submit the PR)
- [X] run tests `npm run test`
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by rosskevin** [comment]
@jamuhl if this looks good to you, I approve it as a patch.

**Comment by jamuhl** [comment]
@rosskevin looks ok to me -  I can merge it later - no problem

**Comment by jamuhl** [comment]
will be published with: https://github.com/i18next/i18next/pull/1451

**Comment by jamuhl** [comment]
was published in 19.4.5

**Pull request merged**
