### PR TITLE
fix: getDataByLanguage type

### PR DESCRIPTION
**Pull request by soso-15315**
Fix an issue where the value and type could be different when getting Data with getDataByLanguage.

If namespace is customized, key may be other than `translation`.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jamuhl** [comment]
@pedrodurek if you got some spare time I would be glad if you can review this PR....thank you

**Comment by adrai** [comment]
lgtm

**Comment by adrai** [comment]
would be nice if you could also add a tyoescript/ test @soso-15315

**Comment by soso-15315** [comment]
@adrai 
thank you!
test added.

**Comment by adrai** [comment]
lgtm

**Comment by adrai** [comment]
thank you for your contribution... it's included in v21.8.16

**Pull request merged**
