### PR TITLE
Parameterized use of TFunction fails while WithT use works

### LINKED ISSUE #1187: Parameterized use of TFunction fails
```ts
function childrenNamespacesConsumer(t: i18next.TFunction, i18n: i18next.i18n) {
  // sanity first - tests from i18next t.test (works)
  const is: string = i18n.t('friend'); // same as <string>
  const io: object = i18n.t<object>('friend');
  const isa: string[] = i18n.t<string[]>('friend');
  const ioa: object[] = i18n.t<object[]>('friend');

  // now try t provided by NamespacesConsumer (fails)
  const s: string = t('friend'); // same as <string>
  const o: object = t<object>('friend');
  const sa: string[] = t<string[]>('friend');
  const oa: object[] = t<object[]>('friend');
}
```

```
Expected 0 type arguments, but got 1.
```

Working on it now, relates to https://github.com/i18next/react-i18next/issues/695

### PR DESCRIPTION
**Pull request by rosskevin**
Closes #1187

### CODE REVIEW

**Comment by rosskevin** [comment]
I'm stumped so far.  Any thoughts @tkow @VincentLanglet ?

**Comment by rosskevin** [comment]
Got it!  Still strange I cannot use an externalized version of `WithT['t']` as `TFunction`.  It appears `TFunction` must be a `type` instead of `interface` to get everything to play nice with generics.

**Comment by rosskevin** [comment]
I guess I'm not quite there yet...so close.

**Comment by rosskevin** [comment]
Ok, finally got it.  It appears with typescript `strict` that `undefined` must be part of the result otherwise usage in option args/props gets too unwieldy.

**Comment by rosskevin** [comment]
@jamuhl this is a patch release.  Please ping me on gitter or twitter and I'll make sure https://github.com/i18next/react-i18next/pull/694 builds - it needs released asap.

**Comment by jamuhl** [comment]
@rosskevin just published i18next@14.0.1

**Comment by VincentLanglet** [comment]
@rosskevin Seems like you found a solution. Good job

**Pull request merged**
