### PR TITLE
Make getFixedT type-safe

### PR DESCRIPTION
**Pull request by pedrodurek**
Closes https://github.com/i18next/i18next/issues/1856

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
Do you want me to release a new patch version or should we wait?

**Comment by pedrodurek** [comment]
@adrai I'll fix [this one](https://github.com/i18next/i18next/pull/1858) first, so we merge together

**Comment by adrai** [comment]
new patch version now?

**Comment by adrai** [comment]
included in v22.0.3

**Pull request merged**
