### PR TITLE
Use explicit imports for utils

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Changes the star imports (import `*`) to explicitly import the utils that are used in each file, this helps with dead code elimination and some code in the resulting build from:
```js
  function pushPath(object, path, newValue, concat) {
    const {
      obj,
      k
    } = getLastOfPath(object, path, Object);
    obj[k] = obj[k] || [];
    if (concat) obj[k] = obj[k].concat(newValue);
    if (!concat) obj[k].push(newValue);
  }
```
to:
```js
  function pushPath(object, path, newValue, concat) {
    const {
      obj,
      k
    } = getLastOfPath(object, path, Object);
    obj[k] = obj[k] || [];
    obj[k].push(newValue);
  }
```
This is because concat is not actually passed to the util function which means the build process can remove the branching as it will always have a deterministic output.

If that changes in the future the code will once again be included so this does not affect any functionality or source code in it self.

PS: I also changed the star imports in the test so it matches the rest of the code for consistency.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [x] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
Thank you Viktor... but I don't see any difference after the build dist/esm/i18next.js looks still the same?

**Comment by VIKTORVAV99** [comment]
> Thank you Viktor... but I don't see any difference after the build dist/esm/i18next.js looks still the same?

ESM build should be the same as it bundles it all in one file and then strips the unused code.

**Comment by adrai** [comment]
So this is only reflected in userland projects? Do you have an example?

**Comment by VIKTORVAV99** [comment]
> So this is only reflected in userland projects? Do you have an example?

The only change I saw was the one mentioned in the PR description when running `npm build` in the top level `i18next.js` and `i18next.min.js`. I did not look into if this propagated to the `udm` or `cjs` bundles as well.

**Comment by adrai** [comment]
I don't see that change there:
image

**Comment by adrai** [comment]
ahhh, now I see it... seems because of new dependencies

**Comment by adrai** [comment]
included in v23.12.1

**Pull request merged**
