### PR TITLE
Provide esm babel helpers for esm build

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by jamuhl** [comment]
does this not also set esModules for the commonjs build?

**Comment by TrySound** [comment]
Commonjs is built without jsnext env
```js
    "build:es": "BABEL_ENV=jsnext babel src --out-dir dist/es",
    "build:cjs": "babel src --out-dir dist/commonjs",
```

**Comment by jamuhl** [comment]
you're right...

**Comment by jamuhl** [comment]
will merge this when I create the next version

**Comment by TrySound** [comment]
I have a few more improvements. Will send after merge.

**Comment by TrySound** [comment]
Why do you need iife, amd and umd at the same time? UMD already supports iife and amd out of the box. I can send PRs with removing them.

**Comment by jamuhl** [comment]
iife and amd are not builded anymore: https://github.com/i18next/i18next/blob/master/package.json#L101 -> build task does not run them...so yes...can be removed

**Comment by TrySound** [comment]
Could you merge this and I will submit PR with bundles

**Pull request merged**
