### PR TITLE
Extend the `init` method with a generic parameter for backend options

### PR DESCRIPTION
**Pull request by 2Pacalypse-**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by 2Pacalypse-** [comment]
Ref: https://github.com/i18next/i18next-http-backend/issues/103

**Comment by adrai** [comment]
lgtm...
Which version increment do you suggest for i18next and for the backends?
major, minor, patch?

**Comment by 2Pacalypse-** [comment]
Probably minor.

**Comment by adrai** [comment]
thank you very much for your contribution...
all version has been released...
I will now proceed to check other backends...

**Pull request merged**
