### PR TITLE
change returnNull default to false

### PR DESCRIPTION
**Pull request by adrai**
#1884

### CODE REVIEW

**Review by pedrodurek — APPROVED** [review]

**Comment by adrai** [comment]
Let's wait to merge this until you "verified" all ts changes.

**Comment by mr-july** [comment]
@adrai: are you aware of the problem with the codeclima check?

**Comment by adrai** [comment]
> @adrai: are you aware of the problem with the codeclima check?

@mr-july was not related to this PR

**Comment by pedrodurek** [comment]
Hey @adrai, omitting `null` from the return type will only work when the resources type is not assigned (when devs opt not to have the keys inferred). Otherwise, it'll iterate over every key and extract the actual literal value. If you move the test to `test/typescript/t.test.ts` it should work. 
If you prefer, we can also change the types for when the resources type is defined to fallback to `string` if the value is `null`, up to you!

**Comment by adrai** [comment]
i18next will return the key if returnNull is false, so maybe it's more consistent if the type would return string in that case?

**Comment by adrai** [comment]
returnNull false having a key value set to false behaves like a non-existing key... so i18next returns the defaultValue or the key name... type string

**Comment by adrai** [comment]
I've moved the test, like you suggested... I think it's ok to have an error when using typesafe translations... (behaves like non-existing keys)

**Pull request merged**
