### PR TITLE
Allow loading remote resources when also using local ones

### PR DESCRIPTION
**Pull request by dyniper**
This change allow simpler bundling of one language and getting other resources remotely. If you think this change is good, i can write unit test for it, but wanted a feel first before i invest more in this.

### CODE REVIEW

**Comment by jamuhl** [comment]
Problem with it - it's breaking and will break consumers production by start fetching data when not expected.

setting resources on init is there and documented as not using any backend implementation, like setting lng on init is omitting detection: -> basically be like all other i18n frameworks

If you like to achieve partial bundling use either the i18next.addResourceBundle to add those initial bundled.

**Comment by jamuhl** [comment]
could you make this change as an optional feature, like eg.:

`if (!this.options.resources || (this.options.partialBundledLanguages && !this.options.resources[this.languages[0]]))`

and use this.languages[0] -> not the detected but the first to load that is whitelisted

**Comment by dyniper** [comment]
That's a good idea. Let me rework this in that vein. The problem with addResourceBundle is that will still try to remotely load the resource on init.

**Comment by jamuhl** [comment]
Feel free to doing another pull request with the changes asked - but i guess due inactivity there is no need anylonger.

closing this for now.

**Pull request closed without merging**
