### PR TITLE
Typescript - Support `const` modifier for `options` and `key`

### PR DESCRIPTION
**Pull request by pedrodurek**
Closes https://github.com/i18next/i18next/issues/1929, https://github.com/i18next/i18next/issues/1950

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [x] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by pedrodurek** [comment]
Hey @adrai, in order to support users with typescript 5+ and older versions, I had to place the types in different files, and now we have two versions of the types for `t` function (`t.d.ts`, `t.v5.d.ts`), please review carefully and let me know if you agree with how I split the resources and if you want me to make any changes.

**Review by adrai — APPROVED** [review]

**Comment by adrai** [comment]
included in 23.4.0

**Comment by efstathiosntonas** [comment]
Hey folks, after this change I get this:

```TS2614: Module  "i18next"  has no exported member  TFunction . Did you mean to use  import TFunction from "i18next"  instead?```

Screenshot 2023-07-29 at 12 00 20

**Comment by abhi-works** [comment]
@pedrodurek  @adrai   Facing below issues while building  with "tsc" after this PR got approved. 
node_modules/i18next/index.d.ts:2:34 - error TS2307: Cannot find module 'typescript/helpers' or its corresponding type declarations.

2 import type { $Dictionary } from 'typescript/helpers';
                                   ~~~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:14:8 - error TS2307: Cannot find module 'typescript/options' or its corresponding type declarations.

14 } from 'typescript/options';
          ~~~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:16:43 - error TS2307: Cannot find module 'typescript/t' or its corresponding type declarations.

16 import type { KeyPrefix, TFunction } from 'typescript/t';
                                             ~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:497:1 - error TS1383: Only named exports may use 'export type'.

497 export type * from 'typescript/options';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:497:20 - error TS2307: Cannot find module 'typescript/options' or its corresponding type declarations.

497 export type * from 'typescript/options';
                       ~~~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:498:1 - error TS1383: Only named exports may use 'export type'.

498 export type * from 'typescript/t';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:498:20 - error TS2307: Cannot find module 'typescript/t' or its corresponding type declarations.

498 export type * from 'typescript/t';
                       ~~~~~~~~~~~~~~

**Comment by adrai** [comment]
@efstathiosntonas @abhi-works sorry, please try with v23.4.1

**Comment by efstathiosntonas** [comment]
@adrai thanks, it works as a charm now.

**Pull request merged**
