### PR TITLE
Add transWrapTextNodes to types

### PR DESCRIPTION
**Pull request by Kamahl19**

### CODE REVIEW

**Comment by jamuhl** [comment]
lgtm

**Comment by adrai** [comment]
@pedrodurek shouldn't this be added in react-i18next?

**Comment by pedrodurek** [comment]
Hey @adrai. Actually, no, it shouldn't. `react-18next` relies on ReactOptions coming from `i18next`.
https://github.com/i18next/react-i18next/blob/master/ts4.1/index.d.ts#L66-L67
https://github.com/i18next/react-i18next/blob/85889f21141950bf9c52e57326fac12231380f86/src/Trans.js#L287

**Comment by adrai** [comment]
The question is, if this could be changed, like the other i18next plugins, like i18next-http-backend?

**Comment by pedrodurek** [comment]
I'll take a look

**Comment by adrai** [comment]
no rush, was just an idea 😉

**Comment by adrai** [comment]
@Kamahl19 released with v20.3.3

**Pull request merged**
