### PR TITLE
Fix Hebrew plural resolver

### PR DESCRIPTION
**Pull request by dutzi**
Source: I speak Hebrew.

### CODE REVIEW

**Comment by dutzi** [comment]
Yeah... I should've actually run the test before making this PR.

**Comment by jamuhl** [comment]
Based on a previous PR https://github.com/i18next/i18next/pull/1121 and unicode/cldr http://www.unicode.org/cldr/charts/36/supplemental/language_plural_rules.html#he hebrew has multiple forms (not that I can judge myself - not speaking it)

@LeonardDrs can you please confirm current rule is correct?

**Comment by LeonardDrs** [comment]
I don't speak hebrew myself, I just noticed that our translate tool wasn't working for hebrew as our plural sentences didn't match the one given by our translators.
Looked up the documentation and did this fix that worked for our translators :grimacing:

**Comment by felixmosh** [comment]
If my suggestion in here https://github.com/i18next/i18next/issues/1374 will be approved, you will able to disable this multiple plurals feature per usage or globally.
@jamuhl WDYT?

**Pull request closed without merging**
