### PR TITLE
perf: Optimize size of Formatter

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Some simple size optimizations, there are no breaking logic or syntax changes.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
thx, included in v23.16.1

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 @adrai This change might reduce code size, but it decreases runtime performance, as the formatters are not cached anymore outside the returned functions as before.
> 
> Before:
> 
> ```js
> number: createCachedFormatter((lng, opt) => {
>   const formatter = new Intl.NumberFormat(lng, { ...opt });
>   return (val) => formatter.format(val);
> }),
> ```
> 
> Returned arrow function uses same formatter on every call. This is even indicated by the function name "createCachedFormatter"!
> 
> After:
> 
> ```js
> number: createCachedFormatter(
>   (lng, opt) => (val) => new Intl.NumberFormat(lng, { ...opt }).format(val),
> ),
> ```
> 
> Returned arrow function creates new formatter on every call.

Do you have a way of actually showing they are not cached anymore? Logically it should be the same as before as new Intl.** was called inside the function return clause before as well, this simply removes the intermediate assignment to a const to take advantage of implicit returns.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Formatter.js#L67

before: it cached the returned function `return (val) => formatter.format(val);` which used the upfront created Intl.*** formatter in it's scope function

`(val) => formatter.format(val);`

now: it creates a new Intl.** formatter and calls format on it...

`(val) => new Intl.NumberFormat(lng, { ...opt }).format(val)`

**Comment by danielrentz** [comment]
I mean calling the inner function that will be returned from the outer function will create a fresh formatter on every call now.

Before, `formats.number` was a function that uses the same formatter living in the closure of the "createCachedFormatter" call:
```js
formats.number === (val) => formatter.format(val)
```
where `formatter` is always the same (created once when the function "createCachedFormatter" has executed once when running the `Formatter` constructor).

Now, `formats.number` is a function that creates a new formatter on every call:
```js
formats.number === (val) => new Intl.NumberFormat(lng, { ...opt }).format(val)
```

**Comment by VIKTORVAV99** [comment]
Hmm I see, might be good to revert that part of the PR then or refractor it so it only returns the outer function but don't call it and then just uses the cached inline function with a call signature instead.

**Comment by adrai** [comment]
Sorry, I did not see that, when reviewing the PR... it's my fault.
Now reverted, and fixed with v23.16.4

**Pull request merged**
