### PR TITLE
null checking codes in getBestMatchFromCodes to not throw JS error wh…

### PR DESCRIPTION
**Pull request by kziechmann**
…en .changeLanguage is called on undefined.

#### Checklist

- [ ] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
May I ask in which situation this happens?

**Comment by kziechmann** [comment]
Hi Adriano, yes I was working with i18next in an express api and when changeLanguage was called with an argument that was not a string (undefined in this case), these .forEach methods were executing and it threw a Javascript error ".forEach is not a method". Maybe there is a better way to handle this scenario?

**Comment by adrai** [comment]
Can you validate the language variable passed to changeLanguage?

Are you using i18next-http-middleware?

**Comment by kziechmann** [comment]
yes, using i18next-http-middleware. I will make sure to validate that
variable in my application, if this isn't an issue elsewhere feel free to
close the pull request.

Kevin Ziechmann
Software Developer
phone: 704.713.5870
linkedIn: linkedin.com/in/kevinziechmann
gitHub: github.com/kziechmann
portfolio: kevinziechmann.me

<http://facebook.com/kevinziechmannphotography>
<https://www.linkedin.com/in/kevin-ziechmann-71966819>

**Comment by adrai** [comment]
Can you try with i18next-http-middleware@3.1.1 ?

**Pull request closed without merging**
