### PR TITLE
Omit object from `t` function

### PR DESCRIPTION
**Pull request by pedrodurek**
Closes (probably): https://github.com/i18next/react-i18next/issues/1559, https://github.com/i18next/next-i18next/issues/1795

There is one downside about the approach proposed here. `t` function will no longer return object unless the option `returnObjects` is `true`. This is not applicable if `t` function is fully type-safe (https://www.i18next.com/overview/typescript), with the enhanced types, we can infer the exact return type.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by renomateo** [comment]
Thanks for working on this!

**Comment by adrai** [comment]
Can you remove the yarn.lock file?

**Comment by pedrodurek** [comment]
Ohhh, sorry my mistake, we definitely can!

**Comment by adrai** [comment]
seems the tests are failing

**Comment by pedrodurek** [comment]
I'm fixing them

**Comment by adrai** [comment]
included in v22.0.3

**Pull request merged**
