### PR TITLE
Add Customizable Retry Logic

### PR DESCRIPTION
**Pull request by mattbjordan**
Added features:

- Set how many retries to perform before giving up
- Set how long the wait should be between retries

See feature request for more details: https://github.com/i18next/i18next/issues/1814

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [x] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided (See feature request: https://github.com/i18next/i18next/issues/1814)
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mattbjordan** [comment]
Does the Cognitive Complexity issue need to get fixed? I'm assuming it's the ternary if statements I added to set the default values if the values passed in were illogical, but the codeclimate link just shows the top of the function, so I'm not clear on if that is causing the complexity issue.

Also, if it is the ternary statements... Any suggestions on what to change it to?

**Comment by adrai** [comment]
I think you can ignore that.

**Comment by adrai** [comment]
lgtm

**Comment by jamuhl** [comment]
lgtm - will merge and publish this next week

**Comment by jamuhl** [comment]
merged....will be published with next update

**Comment by adrai** [comment]
included in v21.9.0

**Pull request merged**
