### PR TITLE
Issue 331 - Merge and overwrite resources

### PR DESCRIPTION
**Pull request by iandarlingmnetics**
Tests have been run in PhantomJS (test:ci/dev)

There's an issue-331-release branch I've pushed too - you can probably ignore that one - I'm only using it for deployment purposes until the code fix lands in master.

### CODE REVIEW

**Comment by jamuhl** [comment]
great...will have a look for next release and integrate this. thanks a lot for your contribution.

**Comment by iandarlingmnetics** [comment]
No problem - if you need anything else on this one let me know.

**Comment by jamuhl** [comment]
closing in favour to https://github.com/i18next/i18next/pull/444

**Comment by iandarlingmnetics** [comment]
Just taken a look at #444, I'll have to test it fits our use case, but looks like it, thank you.

**Pull request closed without merging**
