### PR TITLE
fixed an issue with several unescaped key in the interpolation string

### PR DESCRIPTION
**Pull request by de-robat**
corresponding pull request for issue: https://github.com/i18next/i18next/issues/747 .
please review and let me know what you think. Thanks!

### CODE REVIEW

**Comment by jamuhl** [comment]
there is currently one test failing (compatibility) - will look into this tomorrow

**Comment by de-robat** [comment]
yep i saw it and ressorted to the old way of going with "lastIndex=0" for the unescaped case as well. this leaves the backwards compatibility untouched. Hope the reassesment of travis will proof that :D unfortuneatley i just test with the "npm run tdd" test in the beginning. sry for the inconveniences!

**Comment by jamuhl** [comment]
np...got no time today...so expect it to land tomorrow

**Comment by de-robat** [comment]
ok, tomorrow will be sufficient for me :) Once more: ty!

**Comment by jamuhl** [comment]
thanks you for the contribution: just published i18next@3.3.1 including this fix.

**Pull request merged**
