### PR TITLE
pass used language & namespace to postprocessor

### PR DESCRIPTION
**Pull request by srischard**
for building a cache in the postprocessor I need the used language 

the PR passthrough the used language and used namespace in `options`

fixes https://github.com/i18next/i18next/issues/1340

### CODE REVIEW

**Comment by jamuhl** [comment]
options contain a lot of things...from passed namespace to lngs to use instead of detected...so personally i would prefer it on options -> translator is more a component with fixed api

**Comment by srischard** [comment]
so I moved the parameters to `options`.
But now a collision of option fields might be possible.

**Comment by srischard** [comment]
the codeclimate issue is part of the original code and port of the changed code

**Comment by jamuhl** [comment]
codeclimate is not that important...more important not passing down usedLng, usedNS but the complete resolved as is

**Comment by srischard** [comment]
but passing the whole resolved properties will increase naming collisions for formatting the string.
passing the object at least in a single property `resolved` in `options` I'm only restricted to not use `resolved` im my wording templates.

**Comment by jamuhl** [comment]
why not just rename resolved like I suggested: `{ i18nResolved: resolved, ...options }` 

this way one would have to name a interpolation variable i18nResolved...which is more than unlikely used...and even if used it would be overwritten if options contain it...

**Comment by jamuhl** [comment]
thank you - published in i18next@17.3.0

**Pull request merged**
