### PR TITLE
Preparation to next major release

### PR DESCRIPTION
**Pull request by adrai**
See https://github.com/i18next/i18next/blob/i18next-drop-legacy/CHANGELOG.md#2400 for more information

### CODE REVIEW

**Comment by adrai** [comment]
@VIKTORVAV99 do you like to review?

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 do you like to review?

Would love too but I'm a bit busy today so the soonest I can do it would be tomorrow!

**Comment by adrai** [comment]
ok, will wait for tomorrow...

**Comment by adrai** [comment]
@marcalexiei I updated some deps and now the ts tests fails... maybe you know why? https://github.com/i18next/i18next/pull/2259/commits/f6dd2497c4d6b6d8f5d8ba98e2a8d38e7819b6c2

**Comment by adrai** [comment]
@marcalexiei I tried to fix it like this https://github.com/i18next/i18next/pull/2259/commits/cf33ef56965095c01b166a89f8094087474e1104 Is this correct?

**Comment by marcalexiei** [comment]
I’m busy ATM, I’ll check in a few hours

**Comment by adrai** [comment]
> I’m busy ATM, I’ll check in a few hours

no rush

**Comment by marcalexiei** [comment]
Opened:
- #2260
- #2261

When merged we are good to go for me

**Comment by adrai** [comment]
@VIKTORVAV99 as soon as you give you're OK, we'll merge and release

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 as soon as you give you're OK, we'll merge and release

I'm taking a look at it right now 🙂

**Review by VIKTORVAV99 — APPROVED** [review]
LGTM! 🎉

Thanks for doing this!
I think there is some opportunity to update some more dependencies but hopefully that is not a breaking change and can be done later as well!

**Pull request merged**
