### PR TITLE
test: migrate all tests to vitest

### PR DESCRIPTION
**Pull request by marcalexiei**
Followup to #2098

All tests are now running with `vitest`.

### `test` folder structure changed

To have a better organisation now `test` folder includes 3 children folders:
- `typescript`: includes all typescript workspaces processed dynamically by `vitest.workspace.mts`
- `compatibility`: it was previously stored inside `backward` folder.
- `runtime`: i18n library tests

### Notable test code updates

- `vitest` has deprecated `done` callback so all usage have been changed using `async / await` or `Promise` functions
- There are no longer global variables so everything needs to be explicitly imported
- all tests `*.spec.js` files have renamed with `*.test.js` so we have a consistent pattern for naming test files

### Compatibility tests have been divided into multiple files.

`v1.11.1` was including all tests for backward compatibility so I divided them into multiple files to ease out maintenance efforts.

Shared variables used by these files have been moved inside `v1.i18nInstance.js`

### `circleci` test job image changed to `circleci/node`

Now all tests run in node environment (default in vitest),
so they no longer need a browser to work properly.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
if we don't want to test on browser anymore we can also move to github actions instead of circleci (maybe this helps also with that strange error)

**Comment by marcalexiei** [comment]
I'll give a last try with `watch` option set to `false`.

The odd things I'm not able to replicate this error on my machine in any way

**Comment by marcalexiei** [comment]
[Still hangs out](https://app.circleci.com/pipelines/github/i18next/i18next/1421/workflows/8761ee04-67be-498d-99e0-9b7305c80a7c/jobs/1191)

**Comment by marcalexiei** [comment]
I can try to setup a GitHub actions workflow as you suggested. 
However I think I need your help here to get them up an running.

**Comment by adrai** [comment]
I'll try to setup a github action first for react-i18next...

**Comment by adrai** [comment]
fyi: https://github.com/i18next/react-i18next/compare/8be0c2968dc1f6b79ec8d3249ef0ab7525a488e4..a054a763389adf43e7775de1ff70d731d5927468

**Comment by marcalexiei** [comment]
I'll add a new workflow to this branch file now

**Comment by adrai** [comment]
fyi: https://github.com/i18next/react-i18next/commit/0ef387c0264b5f519f5c848e57ead8f7b6afbfcf

**Comment by adrai** [comment]
I assume we need to add that workflow on master first

**Comment by marcalexiei** [comment]
I added `pull_request` trigger but it seems not working. 
Maybe because the change in on my repo and doesn't trigger actions on `i18next` repo?

**Comment by adrai** [comment]
I'll copy that workflow to the master branch

**Comment by marcalexiei** [comment]
> I assume we need to add that workflow on master first

We can setup the same flow with just lint task on master and I rebase this branch to see if the workflow is triggered

**Comment by adrai** [comment]
ok, you can rebase now

**Comment by adrai** [comment]
looks good

**Comment by marcalexiei** [comment]
Yeah!
The only thing that is missing is coveralls bot message

**Comment by adrai** [comment]
no... it's ok

**Comment by adrai** [comment]
btw: seems there are still some (done) based tests...

**Comment by marcalexiei** [comment]
> btw: seems there are still some (done) based tests...

They were many, I have might lose some of them, sorry. 
Could you please mark them?

-----

I noticed that the lint task is ruined twice. 
My suggestion is to remove `npm run lint` from `pretest` script and eventually add it to `prebuild` and on a `pre-push` what do you think?

**Comment by adrai** [comment]
> My suggestion is to remove `npm run lint` from `pretest` script and eventually add it to `prebuild` script and on a `pre-push` git hook what do you think?

yes, its ok

**Comment by adrai** [comment]
can you also edit the readme: https://github.com/i18next/react-i18next/blob/master/README.md?plain=1#L3 ?

**Comment by adrai** [comment]
> They were many, I have might lose some of them, sorry.
> Could you please mark them?

I just searched for "(done)" here: https://github.com/i18next/i18next/pull/2107/files
image

**Comment by marcalexiei** [comment]
> My suggestion is to remove npm run lint from pretest script and eventually add it to prebuild script and on a pre-push git hook what do you think?

I prefer to open a separate PR for this. This already has a lot of modification 😅

----

> can you also edit the readme: https://github.com/i18next/react-i18next/blob/master/README.md?plain=1#L3?

Sure


---- 

> I just searched for "(done)" here: https://github.com/i18next/i18next/pull/2107/files

Gotcha. Thanks

**Comment by marcalexiei** [comment]
The `backendConnector.load.retry.test.skip.js` was skipped from old tests so I haven't changed it. 

However I found a test with a done on `i18next.backend.concurrentLoad.test.js`.

I'll update them shortly

**Comment by adrai** [comment]
Those are just skipped for ci/cd, but occasionally we run them locally

**Comment by adrai** [comment]
fyi: this also seems to work: https://github.com/i18next/react-i18next/compare/04a8e0c2734c7a8fa948f3d0090543a76dbe2e2b..2d0424d8da3259a9e5c9f6f2033dce3fbfd63bba

**Comment by adrai** [comment]
> > My suggestion is to remove npm run lint from pretest script and eventually add it to prebuild script and on a pre-push git hook what do you think?
> 
> I prefer to open a separate PR for this. This already has a lot of modification 😅

alternatively, we can just remove the lint step in the workflow and keep the rest as is

**Comment by adrai** [comment]
lgtm

**Comment by marcalexiei** [comment]
Yes, that should be all!

When I have time I would like to try enable eslint on test folder and maybe try a more strict typescript-eslint.

**Comment by adrai** [comment]
thank you for your awesome work...
btw: what is the best way to run these tests? `test/runtime/**/*.test.local.*`

**Comment by marcalexiei** [comment]
> btw: what is the best way to run these tests? test/runtime/**/*.test.local.*

I was using inline CLI commands of `vitest` but now that you point it out it's not a great dev experience. 
Alternatively you have to rename them removing .local. which is also not good...

Maybe I should create a separate workspace for them. This should be the more clean and easy solution.
I'll setup a PR in the afternoon.

Thanks for pointing this out!

**Comment by adrai** [comment]
I have to thank you. 🙏

**Pull request merged**
