### PR TITLE
Add typescript testing

### PR DESCRIPTION
**Pull request by tkow**
- Separate Pull requests of https://github.com/i18next/i18next/pull/1164

If it isn't needed, close it.

### CODE REVIEW

**Comment by rosskevin** [comment]
@jamuhl is travis not running the `test` script?  This PR should be broken at this point, I was just checkpointing some changes to the ts setup and I know they are broken locally.  Sinc. `show all checks` just shows code climate I'm concerned that PRs are not being tested.

**Comment by jamuhl** [comment]
@rosskevin shows failed on https://travis-ci.org/i18next/i18next but not here...will need to check why

**Comment by rosskevin** [comment]
oh, shows building now...

**Comment by jamuhl** [comment]
@rosskevin still worked here: https://github.com/i18next/i18next/pull/1163

**Comment by jamuhl** [comment]
@rosskevin might have been just a glitch

**Pull request merged**
