### PR TITLE
Change point to main file

### LINKED ISSUE #477: webpack pre-built javascript warning
When I use webpack to bundle, it complaint something like this.
```
WARNING in ./~/i18next/bin/index.js
Critical dependencies:
1:409-416 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/i18next/bin/index.js 1:409-416
```
To clear this warning, I need to change the `package.json`  file.
```
"main": "./lib/index.js",
```
or `import 'i18next' from 'i18next/lib/index.js`.
I`m not sure this warning need to optimize.
Thanks for your time.

### PR DESCRIPTION
**Pull request by just-boris**
As I see, it can't break anything
fixes #477

### CODE REVIEW

**Comment by jamuhl** [comment]
will change this for next minor version. might be best solution for now.

**Comment by just-boris** [comment]
That will be good for me.
Thanks!

**Comment by jamuhl** [comment]
v2.2.0 published

**Comment by mathieumg** [comment]
@jamuhl  Are there plans to publish the same change for the official backends? Are you open to PRs for that change? Thanks!

**Comment by jamuhl** [comment]
@mathieumg yes would do that when getting to it...but PRs would be great (would speed it up).

**Pull request merged**
