### PR TITLE
Type ResourceStore

### LINKED ISSUE #1364: Typescript: type of "i18next.services.resourceStore" is wrong
I'm trying to access the resource store datas for Server Side Rendering.

I use: `i18next.services.resourceStore`, witch is of type 'Resource'
I expect `i18next.services.resourceStore['en']` to work, but instead I have to do:
`i18next.services.resourceStore.data['en']`

That data property does not exist for Typescript. It looks like i18next.services.resourceStore is not of ResourceType, but i18next.services.resourceStore.data is. Maybe a 'ResourceStore' is missing in the middle?

### PR DESCRIPTION
**Pull request by rosskevin**
This is my interpretation of the runtime code and requires review for accuracy

Closes #1364

/cc @fromi

### CODE REVIEW

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/issues/1364#issuecomment-559687028 not against this...but it's in the gray shade of private/publich API

**Comment by rosskevin** [comment]
I'm good with this as long as it is factually representative, even though it may not be preferred access.

**Comment by rosskevin** [comment]
This can be a patch release

**Comment by jamuhl** [comment]
was published in i18next@19.0.2

**Pull request merged**
