### PR TITLE
Bundle all entry points with rollup

### PR DESCRIPTION
**Pull request by TrySound**
Similar to https://github.com/i18next/i18next-chained-backend/pull/8

### CODE REVIEW

**Comment by jamuhl** [comment]
thanks again...really appreciate your help with all this

published in i18next@16.0.0

**Comment by TrySound** [comment]
My pleasure

**Comment by jamuhl** [comment]
@TrySound how you handle that problem nowadays: https://github.com/i18next/i18next-express-middleware/pull/182/files#diff-1fdf421c05c1140f6d71444ea2b27638L32

in the past pkg.main was https://github.com/i18next/i18next/blob/master/index.js to avoid this problem of default export

**Comment by jamuhl** [comment]
@TrySound my suggestion would be to remove those https://github.com/i18next/i18next/blob/master/src/index.js#L5 named export shortcuts to most used functions

-> they once were added on request to get things like `import { changeLanguage } from 'i18next'`

but was never a big fan of that (hides the i18next is an instance of a class where you can have multiple during runtime if needed)...

**Comment by jamuhl** [comment]
@TrySound made that change in i18next@17.0.0 and also removed the build artefact from root

**Comment by TrySound** [comment]
Ah, cool. Yeah, mixing default and named exports usually leads to problems like this.

**Pull request merged**
